-- Insert sample hotels
INSERT INTO hotels (name, description, location_city, location_country, location_lat, location_lng, images, amenities, rating, review_count, price_per_night, currency) VALUES
('Grand Ocean Resort', 'Luxury beachfront resort with stunning ocean views and world-class amenities', 'Bali', 'Indonesia', -8.3405, 115.0920, '["https://example.com/hotel1_1.jpg", "https://example.com/hotel1_2.jpg"]', '["Wifi", "Pool", "Gym", "Parking", "Spa", "Restaurant"]', 4.8, 1247, 89.00, 'USD'),
('Tokyo Central Hotel', 'Modern hotel in the heart of Tokyo with easy access to major attractions', 'Tokyo', 'Japan', 35.6762, 139.6503, '["https://example.com/hotel2_1.jpg", "https://example.com/hotel2_2.jpg"]', '["Wifi", "Gym", "Coffee", "Parking", "Business Center"]', 4.6, 892, 156.00, 'USD'),
('Santorini Sunset Villa', 'Romantic villa with breathtaking sunset views over the Aegean Sea', 'Santorini', 'Greece', 36.3932, 25.4615, '["https://example.com/hotel3_1.jpg", "https://example.com/hotel3_2.jpg"]', '["Wifi", "Pool", "Coffee", "Terrace", "Kitchen"]', 4.9, 567, 234.00, 'USD'),
('Paris Boutique Hotel', 'Charming boutique hotel near the Eiffel Tower with French elegance', 'Paris', 'France', 48.8566, 2.3522, '["https://example.com/hotel4_1.jpg", "https://example.com/hotel4_2.jpg"]', '["Wifi", "Coffee", "Gym", "Concierge", "Room Service"]', 4.7, 1034, 178.00, 'USD'),
('Swiss Alpine Lodge', 'Cozy mountain lodge with spectacular Alpine views and ski access', 'Zermatt', 'Switzerland', 46.0207, 7.7491, '["https://example.com/hotel5_1.jpg", "https://example.com/hotel5_2.jpg"]', '["Wifi", "Spa", "Restaurant", "Ski Storage", "Fireplace"]', 4.5, 623, 295.00, 'USD'),
('Dubai Marina Resort', 'Luxurious resort overlooking Dubai Marina with premium amenities', 'Dubai', 'UAE', 25.0772, 55.1395, '["https://example.com/hotel6_1.jpg", "https://example.com/hotel6_2.jpg"]', '["Wifi", "Pool", "Gym", "Spa", "Beach Access", "Valet"]', 4.7, 1156, 189.00, 'USD');

-- Insert sample destinations
INSERT INTO destinations (name, country, description, images, attractions, best_time_to_visit, average_temperature, popular_activities, coordinates_lat, coordinates_lng) VALUES
('Bali', 'Indonesia', 'Tropical paradise known for its beautiful beaches, ancient temples, and vibrant culture', '["https://example.com/bali1.jpg", "https://example.com/bali2.jpg"]', '["Tanah Lot Temple", "Ubud Rice Terraces", "Mount Batur", "Seminyak Beach"]', 'April to October', '26-30°C', '["Surfing", "Temple Tours", "Yoga Retreats", "Cultural Experiences"]', -8.3405, 115.0920),
('Tokyo', 'Japan', 'Dynamic metropolis blending traditional culture with cutting-edge technology', '["https://example.com/tokyo1.jpg", "https://example.com/tokyo2.jpg"]', '["Senso-ji Temple", "Tokyo Skytree", "Shibuya Crossing", "Tsukiji Fish Market"]', 'March to May, September to November', '15-25°C', '["City Tours", "Food Experiences", "Shopping", "Cultural Activities"]', 35.6762, 139.6503),
('Santorini', 'Greece', 'Stunning Greek island famous for its white-washed buildings and spectacular sunsets', '["https://example.com/santorini1.jpg", "https://example.com/santorini2.jpg"]', '["Oia Village", "Red Beach", "Akrotiri Archaeological Site", "Fira Town"]', 'April to October', '20-28°C', '["Sunset Viewing", "Wine Tasting", "Beach Activities", "Photography"]', 36.3932, 25.4615),
('Paris', 'France', 'City of Light renowned for its art, fashion, gastronomy, and culture', '["https://example.com/paris1.jpg", "https://example.com/paris2.jpg"]', '["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées"]', 'April to June, September to October', '12-20°C', '["Museum Tours", "Fine Dining", "Shopping", "River Cruises"]', 48.8566, 2.3522),
('Swiss Alps', 'Switzerland', 'Majestic mountain range offering world-class skiing and breathtaking scenery', '["https://example.com/alps1.jpg", "https://example.com/alps2.jpg"]', '["Matterhorn", "Jungfraujoch", "Lake Geneva", "Rhine Falls"]', 'December to March (skiing), June to September (hiking)', '5-15°C', '["Skiing", "Hiking", "Mountain Climbing", "Scenic Railways"]', 46.0207, 7.7491),
('Dubai', 'UAE', 'Futuristic city known for luxury shopping, ultramodern architecture, and desert adventures', '["https://example.com/dubai1.jpg", "https://example.com/dubai2.jpg"]', '["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Dubai Marina"]', 'November to March', '25-35°C', '["Shopping", "Desert Safari", "Luxury Dining", "Architecture Tours"]', 25.0772, 55.1395);

-- Insert sample travel packages
INSERT INTO travel_packages (title, description, duration, destinations, inclusions, price, currency, images, rating, difficulty, max_guests) VALUES
('Bali Adventure Package', 'Explore the best of Bali with temple tours, beach activities, and cultural experiences', 7, '["Bali"]', '["Accommodation", "Breakfast", "Temple Tours", "Airport Transfer", "Cultural Activities"]', 1299.00, 'USD', '["https://example.com/pkg1_1.jpg", "https://example.com/pkg1_2.jpg"]', 4.8, 'easy', 8),
('Japan Cultural Journey', 'Immerse yourself in Japanese culture with visits to Tokyo and Kyoto', 10, '["Tokyo", "Kyoto"]', '["Accommodation", "Breakfast", "Train Pass", "Cultural Tours", "Traditional Ryokan Stay"]', 2499.00, 'USD', '["https://example.com/pkg2_1.jpg", "https://example.com/pkg2_2.jpg"]', 4.9, 'moderate', 12),
('European Grand Tour', 'Visit 5 European countries and experience their rich history and culture', 14, '["Paris", "Rome", "Barcelona", "Amsterdam", "Prague"]', '["Accommodation", "Breakfast", "Train Travel", "City Tours", "Museum Passes"]', 3299.00, 'USD', '["https://example.com/pkg3_1.jpg", "https://example.com/pkg3_2.jpg"]', 4.7, 'moderate', 16),
('Swiss Alpine Adventure', 'Experience the beauty of the Swiss Alps with skiing, hiking, and scenic railways', 8, '["Swiss Alps"]', '["Accommodation", "Breakfast", "Ski Pass", "Mountain Railways", "Equipment Rental"]', 2199.00, 'USD', '["https://example.com/pkg4_1.jpg", "https://example.com/pkg4_2.jpg"]', 4.6, 'challenging', 10),
('Dubai Luxury Experience', 'Indulge in the ultimate luxury experience in Dubai with premium accommodations and exclusive tours', 5, '["Dubai"]', '["5-Star Accommodation", "All Meals", "Desert Safari", "City Tours", "Shopping Experience"]', 1899.00, 'USD', '["https://example.com/pkg5_1.jpg", "https://example.com/pkg5_2.jpg"]', 4.8, 'easy', 6),
('Mediterranean Island Hopping', 'Discover the beauty of Greek islands with this comprehensive island-hopping adventure', 12, '["Santorini", "Mykonos", "Crete"]', '["Accommodation", "Breakfast", "Ferry Transfers", "Island Tours", "Beach Activities"]', 2799.00, 'USD', '["https://example.com/pkg6_1.jpg", "https://example.com/pkg6_2.jpg"]', 4.7, 'moderate', 14);
