-- Insert sample hotels
INSERT INTO hotels (id, name, description, location_city, location_country, location_lat, location_lng, images, amenities, rating, review_count, price_per_night, currency) VALUES
('hotel_1', 'Grand Ocean Resort', 'Luxury beachfront resort with stunning ocean views and world-class amenities', 'Bali', 'Indonesia', -8.3405, 115.0920, '["https://example.com/hotel1_1.jpg", "https://example.com/hotel1_2.jpg"]', '["Wifi", "Pool", "Gym", "Parking", "Spa", "Restaurant"]', 4.8, 1247, 89.00, 'USD'),
('hotel_2', 'Tokyo Central Hotel', 'Modern hotel in the heart of Tokyo with easy access to major attractions', 'Tokyo', 'Japan', 35.6762, 139.6503, '["https://example.com/hotel2_1.jpg", "https://example.com/hotel2_2.jpg"]', '["Wifi", "Gym", "Coffee", "Parking", "Business Center"]', 4.6, 892, 156.00, 'USD'),
('hotel_3', 'Santorini Sunset Villa', 'Romantic villa with breathtaking sunset views over the Aegean Sea', 'Santorini', 'Greece', 36.3932, 25.4615, '["https://example.com/hotel3_1.jpg", "https://example.com/hotel3_2.jpg"]', '["Wifi", "Pool", "Coffee", "Terrace", "Kitchen"]', 4.9, 567, 234.00, 'USD'),
('hotel_4', 'Paris Boutique Hotel', 'Charming boutique hotel near the Eiffel Tower with French elegance', 'Paris', 'France', 48.8566, 2.3522, '["https://example.com/hotel4_1.jpg", "https://example.com/hotel4_2.jpg"]', '["Wifi", "Coffee", "Gym", "Concierge", "Room Service"]', 4.7, 1034, 178.00, 'USD');

-- Insert sample destinations
INSERT INTO destinations (id, name, country, description, images, attractions, best_time_to_visit, average_temperature, popular_activities, coordinates_lat, coordinates_lng) VALUES
('dest_1', 'Bali', 'Indonesia', 'Tropical paradise known for its beautiful beaches, ancient temples, and vibrant culture', '["https://example.com/bali1.jpg", "https://example.com/bali2.jpg"]', '["Tanah Lot Temple", "Ubud Rice Terraces", "Mount Batur", "Seminyak Beach"]', 'April to October', '26-30°C', '["Surfing", "Temple Tours", "Yoga Retreats", "Cultural Experiences"]', -8.3405, 115.0920),
('dest_2', 'Tokyo', 'Japan', 'Dynamic metropolis blending traditional culture with cutting-edge technology', '["https://example.com/tokyo1.jpg", "https://example.com/tokyo2.jpg"]', '["Senso-ji Temple", "Tokyo Skytree", "Shibuya Crossing", "Tsukiji Fish Market"]', 'March to May, September to November', '15-25°C', '["City Tours", "Food Experiences", "Shopping", "Cultural Activities"]', 35.6762, 139.6503),
('dest_3', 'Santorini', 'Greece', 'Stunning Greek island famous for its white-washed buildings and spectacular sunsets', '["https://example.com/santorini1.jpg", "https://example.com/santorini2.jpg"]', '["Oia Village", "Red Beach", "Akrotiri Archaeological Site", "Fira Town"]', 'April to October', '20-28°C', '["Sunset Viewing", "Wine Tasting", "Beach Activities", "Photography"]', 36.3932, 25.4615),
('dest_4', 'Paris', 'France', 'City of Light renowned for its art, fashion, gastronomy, and culture', '["https://example.com/paris1.jpg", "https://example.com/paris2.jpg"]', '["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées"]', 'April to June, September to October', '12-20°C', '["Museum Tours", "Fine Dining", "Shopping", "River Cruises"]', 48.8566, 2.3522);

-- Insert sample travel packages
INSERT INTO travel_packages (id, title, description, duration, destinations, inclusions, price, currency, images, rating, difficulty, max_guests) VALUES
('pkg_1', 'Bali Adventure Package', 'Explore the best of Bali with temple tours, beach activities, and cultural experiences', 7, '["Bali"]', '["Accommodation", "Breakfast", "Temple Tours", "Airport Transfer", "Cultural Activities"]', 1299.00, 'USD', '["https://example.com/pkg1_1.jpg", "https://example.com/pkg1_2.jpg"]', 4.8, 'easy', 8),
('pkg_2', 'Japan Cultural Journey', 'Immerse yourself in Japanese culture with visits to Tokyo and Kyoto', 10, '["Tokyo", "Kyoto"]', '["Accommodation", "Breakfast", "Train Pass", "Cultural Tours", "Traditional Ryokan Stay"]', 2499.00, 'USD', '["https://example.com/pkg2_1.jpg", "https://example.com/pkg2_2.jpg"]', 4.9, 'moderate', 12),
('pkg_3', 'European Grand Tour', 'Visit 5 European countries and experience their rich history and culture', 14, '["Paris", "Rome", "Barcelona", "Amsterdam", "Prague"]', '["Accommodation", "Breakfast", "Train Travel", "City Tours", "Museum Passes"]', 3299.00, 'USD', '["https://example.com/pkg3_1.jpg", "https://example.com/pkg3_2.jpg"]', 4.7, 'moderate', 16);
